DROP TABLE IF EXISTS `map_challenge_mode`;
CREATE TABLE `map_challenge_mode` (
  `Name` TEXT COLLATE utf8mb4_unicode_ci,
  `ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `MapID` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '0',
  `CriteriaCount1` SMALLINT(6) NOT NULL DEFAULT '0',
  `CriteriaCount2` SMALLINT(6) NOT NULL DEFAULT '0',
  `CriteriaCount3` SMALLINT(6) NOT NULL DEFAULT '0',
  `Flags` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `VerifiedBuild` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`,`VerifiedBuild`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `map_challenge_mode_locale`;
CREATE TABLE `map_challenge_mode_locale` (
  `ID` INT(10) UNSIGNED NOT NULL DEFAULT '0',
  `locale` VARCHAR(4) COLLATE utf8mb4_unicode_ci NOT NULL,
  `Name_lang` TEXT COLLATE utf8mb4_unicode_ci,
  `VerifiedBuild` INT(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`,`locale`,`VerifiedBuild`)
) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!50500 PARTITION BY LIST  COLUMNS(locale)
(PARTITION deDE VALUES IN ('deDE') ENGINE = InnoDB,
 PARTITION esES VALUES IN ('esES') ENGINE = InnoDB,
 PARTITION esMX VALUES IN ('esMX') ENGINE = InnoDB,
 PARTITION frFR VALUES IN ('frFR') ENGINE = InnoDB,
 PARTITION itIT VALUES IN ('itIT') ENGINE = InnoDB,
 PARTITION koKR VALUES IN ('koKR') ENGINE = InnoDB,
 PARTITION ptBR VALUES IN ('ptBR') ENGINE = InnoDB,
 PARTITION ruRU VALUES IN ('ruRU') ENGINE = InnoDB,
 PARTITION zhCN VALUES IN ('zhCN') ENGINE = InnoDB,
 PARTITION zhTW VALUES IN ('zhTW') ENGINE = InnoDB) */





